<?php

/*
 * This file is part of Contao.
 *
 * Copyright (c) 2005-2017 Leo Feyer
 *
 * @license LGPL-3.0+
 */

namespace Contao\ManagerPlugin\Composer;

use Composer\Package\Locker;
use Composer\Package\RootPackageInterface;
use Contao\ManagerPlugin\Dependency\DependencyResolverTrait;
use Contao\ManagerPlugin\Dependency\DependentPluginInterface;
use Contao\ManagerPlugin\Dependency\UnresolvableDependenciesException;

class Installer
{
    use DependencyResolverTrait;

    private static $generatedClassTemplate = <<<'PHP'
<?php

/*
 * This file is part of Contao.
 *
 * Copyright (c) 2005-2017 Leo Feyer
 *
 * @license LGPL-3.0+
 */

namespace Contao\ManagerPlugin;

/**
 * This class is generated by contao/manager-bundle, specifically by
 * @see \Contao\ManagerBundle\Composer\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
%s
{
    const BUNDLE_PLUGINS = 'Contao\ManagerPlugin\Bundle\BundlePluginInterface';
    const CONFIG_PLUGINS = 'Contao\ManagerPlugin\Config\ConfigPluginInterface';
    const EXTENSION_PLUGINS = 'Contao\ManagerPlugin\Config\ExtensionPluginInterface';
    const ROUTING_PLUGINS = 'Contao\ManagerPlugin\Routing\RoutingPluginInterface';

    /**
     * @var array
     */
    private $plugins;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->plugins = %s;
    }

    /**
     * Returns all active plugin instances.
     *
     * @return array
     */
    public function getInstances()
    {
        return $this->plugins;
    }

    /**
     * Returns the active plugin instances of a given type (see class constants).
     *
     * @param string $type
     * @param bool   $reverseOrder
     *
     * @return array
     */
    public function getInstancesOf($type, $reverseOrder = false)
    {
        $plugins = array_filter(
            $this->getInstances(),
            function ($plugin) use ($type) {
                return is_a($plugin, $type);
            }
        );

        $plugins = $reverseOrder ? array_reverse($plugins, true) : $plugins;

        return $plugins;
    }
}

PHP;

    /**
     * Sets the Contao Manager plugins.
     *
     * @param Locker               $locker
     * @param RootPackageInterface $rootPackage
     *
     * @throws \RuntimeException
     */
    public function dumpPlugins(Locker $locker, RootPackageInterface $rootPackage)
    {
        $plugins = [];

        $disabled = $this->getDisabledPackages($rootPackage);
        $lockData = $locker->getLockData();
        $lockData['packages-dev'] = isset($lockData['packages-dev']) ? $lockData['packages-dev'] : [];

        foreach (array_merge($lockData['packages'], $lockData['packages-dev']) as $package) {
            if (in_array($package['name'], $disabled, true)) {
                continue;
            }

            if (isset($package['extra']['contao-manager-plugin'])) {
                if (!class_exists($package['extra']['contao-manager-plugin'])) {
                    throw new \RuntimeException(
                        sprintf('Plugin class "%s" not found', $package['extra']['contao-manager-plugin'])
                    );
                }

                $plugins[$package['name']] = new $package['extra']['contao-manager-plugin']();
            }
        }

        $plugins = $this->orderPlugins($plugins);

        // Instantiate a global plugin to load AppBundle or other customizations
        $appPlugin = '\ContaoManagerPlugin';

        if (class_exists($appPlugin)) {
            $plugins['app'] = new $appPlugin();
        }

        $this->dumpClass($plugins);
    }

    private function getDisabledPackages(RootPackageInterface $rootPackage)
    {
        $extra = $rootPackage->getExtra();

        if (!isset($extra['contao-manager']['disabled-packages'])) {
            return [];
        }

        return (array) $extra['contao-manager']['disabled-packages'];
    }

    /**
     * Dumps the PluginLoader class.
     */
    private function dumpClass(array $plugins)
    {
        $content = sprintf(
            static::$generatedClassTemplate,
            'cla' . 'ss ' . 'PluginLoader', // note: workaround for regex-based code parsers :-(
            'unserialize('.var_export(serialize($plugins), true).')'
        );

        file_put_contents(__DIR__.'/../PluginLoader.php', $content);
    }

    /**
     * Orders the plugins.
     *
     * @param array $plugins
     *
     * @throws UnresolvableDependenciesException
     *
     * @return array
     */
    private function orderPlugins(array $plugins)
    {
        $ordered = [];
        $dependencies = [];
        $packages = array_keys($plugins);

        // Load the manager bundle first
        if (isset($plugins['contao/manager-bundle'])) {
            array_unshift($packages, 'contao/manager-bundle');
            $packages = array_unique($packages);
        }

        // Walk through the packages
        foreach ($packages as $packageName) {
            $dependencies[$packageName] = [];

            if ($plugins[$packageName] instanceof DependentPluginInterface) {
                $dependencies[$packageName] = $plugins[$packageName]->getPackageDependencies();
            }
        }

        foreach ($this->orderByDependencies($dependencies) as $packageName) {
            $ordered[$packageName] = $plugins[$packageName];
        }

        return $ordered;
    }
}
